spring.application.name=kursach

spring.datasource.url=jdbc:postgresql://localhost:5432/shop_network
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ?????? ???????????
logging.level.root=WARN
logging.level.com.shop=INFO
logging.level.com.shop.controller=INFO
logging.level.com.shop.service=INFO
logging.level.com.shop.audit=INFO

logging.file.name=logs/audit.log
logging.file.path=logs

# ?????? ?????
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n

# ??????? ?????
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

?6uRMalda